### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by jackosan** [sijan8s3/Jump-Jam-Game#2]
Hey!

I would like to contribute to your project for this year's Hacktoberfest. Would there be some tasks/issues you would like me to work on?

Best regards,
Jack

**Comment by sijan8s3** [comment]
sure!
I was working on this following 'coding in flow' yt tutorial for a 2D game,
unable to complete due to other projects,
you can surely add some contribution towards the completion!
I may have completed up to video 4!

**Comment by jackosan** [comment]
Well, in that case if it is not going to be continued I have contributed with a music player just for fun :D

**Comment by sijan8s3** [comment]
i'm going to continue it soon,
i'm not going to leave this incomplete! 
so, please do quality contribution!

**Comment by jackosan** [comment]
Understood, I shall contribute something of worth!
